AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false 

Style/FrozenStringLiteralComment:
  Enabled: false